# Site settings
title: Community Organizer
email: seshagiriprabhu@gmail.com
url: https://seshagiriprabhu.github.io/Community-AndroidApp
description: "Implementation of location based decentralized community app for research purpose"
baseurl: "/Community-AndroidApp"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
    primary: 18bc9c #80B3FF
    secondary: 2c3e50 #FD6E8A
    secondary-dark: 233140 #A2122F


# Footer settings
footer:
    copyright: Community Organizer

author1: 
    name: Hari Raghavendar
    url:
    image: "img/images/hari.jpg"

author2:
    name: Seshagiri Prabhu
    url: https://seshagiriprabhu.wordpress.com/
    image: "img/images/giri.jpg"

supervisor: 
    name: Dr. David Koll
    url: http://user.informatik.uni-goettingen.de/~dkoll/
    image: "img/images/david.jpg"  


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/seshagiriprabhu/Community-AndroidApp

# Postal address (add as many lines as necessary)
address:
    - line: Informatics Department
    - line: Georg-August-University
    - line: Gottingen, Germany

address-details:
    name: Computer Networks Group
    url: https://wiki.net.informatik.uni-goettingen.de/


# Build settings
name: Community Organizer
markdown: kramdown
permalink: pretty
